version: '3'
services:

  app:
    build: .
    container_name: projectopia-app
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    depends_on:
      mysql: 
        condition: service_healthy
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: projectopia-database
      DATABASE_USER: user
      DATABASE_PASSWORD: user
      REDIS_URL: 'redis://redis:6379'
      PORT: 3000
      BASE_URL: '/api'
      JWT_EXPIRATION_TIME: '12h'
      JWT_SECRET_KEY: 'H+MbQeThWmYq3t6w9z$C&F)J@NcRfUjX'

  mysql:
    image: mysql:latest
    container_name: obl-database
    depends_on:
      - redis
    environment:
      MYSQL_ROOT_PASSWORD: projectopia
      MYSQL_DATABASE: projectopia-database
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - '3306:3306'
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=projectopia --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  redis:
    image: redis:latest
    container_name: projectopia-redis
    ports:
      - '6379:6379'